# Generated by Django 4.0.3 on 2022-03-28 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phonenumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
