# Generated by Django 4.0.3 on 2022-03-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
