# Generated by Django 4.0.3 on 2022-04-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_amount_alter_payment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='phonenumber',
        ),
    ]
