# Generated by Django 4.0.3 on 2022-04-02 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_user_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
