# Generated by Django 4.0.3 on 2022-03-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default='First_product', max_length=255),
        ),
    ]
