# Generated by Django 4.0.3 on 2022-03-14 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_four',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
