# Generated by Django 4.0.3 on 2022-03-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_name_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
