# Generated by Django 3.1 on 2022-05-31 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
