# Generated by Django 3.2 on 2022-07-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time_slot',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
