# Generated by Django 3.1 on 2022-05-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbase_email_alter_userbase_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
