# Generated by Django 4.0.3 on 2022-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_address1_order_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_paid',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(max_length=200),
        ),
    ]
