# Generated by Django 4.0.3 on 2022-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
