# Generated by Django 3.1 on 2022-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220526_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
