# Generated by Django 3.1 on 2022-05-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='channel',
        ),
    ]
